name: Integration Tests
on:
  workflow_dispatch:
  pull_request:
    branches-ignore: ['llvm-**']
  merge_group:
    branches: [main, 'dev-**']
    types: [checks_requested]
  push:
    branches: [main]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
permissions: read-all

jobs:

  pre-commit:
    uses: ./.github/workflows/pre-commit.yml
