name: Integration Tests CPU

on:
  workflow_call:
    inputs:
      matrix:
        required: true
        type: string

jobs:
  integration-tests-cpu:
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 60
    strategy:
      matrix:
        runner: ${{ fromJson(inputs.matrix) }}
    env:
      RUNNER_TYPE: ${{ matrix.runner[0] }}
      TRITON_BUILD_WITH_CCACHE: "true"
      TRITON_BUILD_WITH_CLANG_LLD: "TRUE"
      TRITON_USE_ASSERT_ENABLED_LLVM: "TRUE"
      TRITON_DISABLE_LINE_INFO: 1
      PROTON_SKIP_PC_SAMPLING_TEST: 1
      PYTHON: "python3"
      CCACHE_COMPRESS: "true"
    steps:
      - name: Install ccache and boost
        run: sudo apt-get update && sudo apt-get install -y ccache libboost-fiber-dev
      - name: Checkout CPU Plugin
        uses: actions/checkout@v5
      - name: Fetch Triton upstream Commit Hash
        shell: bash
        run: |
          TRITON_COMMIT_HASH="$(cat triton.txt)"
          echo "Found Triton commit hash: ${TRITON_COMMIT_HASH}"
          echo "triton_commit_hash=${TRITON_COMMIT_HASH}" >> ${GITHUB_ENV}
      - name: Checkout Triton upstream repo
        uses: actions/checkout@v5
        with:
          repository: triton-lang/triton
          path: triton
          submodules: true
          ref: ${{ env.triton_commit_hash }}
      - name: Apply Triton patches
        working-directory: ./triton
        run: |
          git apply -v ${GITHUB_WORKSPACE}/.github/patches/*.patch
      - name: Compute cache keys
        id: cache-key
        run: |
          triton_file="${GITHUB_WORKSPACE}/triton.txt"

          # Check if files exist before proceeding
          if [[ ! -f "$triton_file" ]]; then
            echo "Error: Required dependency files are missing."
            exit 1
          fi

          # Process the files if they exist
          echo "triton=$(cat $triton_file | cut -c 1-8)" >> $GITHUB_OUTPUT
        shell: bash
      - name: Cache build dependencies
        uses: actions/cache@v4
        with:
          # Note that we cannot use environment variables here given there is
          # no shell to interpret them in the paths.
          path: |
            ~/.triton/llvm
            ~/.triton/nvidia
            ~/.triton/json
          key: ${{ runner.os }}-${{ runner.arch }}-triton-${{ steps.cache-key.outputs.triton }}
      - name: Inspect cache directories
        run: |
          mkdir -p ~/.triton
          du -h -d 1 ~/.triton

          mkdir -p ~/.ccache
          du -h -d 1 ~/.ccache
      - name: Update PATH
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install torch
        run: |
          python -m pip install --upgrade pip
          python -m pip install torch==2.9.0 --index-url https://download.pytorch.org/whl/test/cpu
          pip freeze
      - name: Install Triton
        working-directory: ./triton
        run: |
          nproc
          echo "PATH is '$PATH'"
          ccache --zero-stats
          MAX_JOBS=8 TRITON_PLUGIN_DIRS=${GITHUB_WORKSPACE} make dev-install
      - name: CCache Stats
        run: ccache --print-stats
      - name: Run lit tests
        working-directory: ./triton
        run: |
          make test-lit
          export BUILD_DIR="$(cd python; python -c 'from build_helpers import get_cmake_dir; print(get_cmake_dir())')"
          ninja -C ${BUILD_DIR} check-triton-cpu-lit-tests
      - name: Run python tests on CPU
        working-directory: ./triton
        run: |
          TRITON_CPU_NUM_WARPS=4 python -m pytest --device "cpu" python/test/unit/language/test_core.py -k "(test_reduce1d or test_load_store_same_ptr) and not test_reduce1d[1-sum-float16-512]"
          python -m pytest --device "cpu" python/test/unit/runtime/test_launch.py -k "not test_launch_with_options"
      - name: Run tutorial 01 on CPU
        working-directory: ./triton
        run: |
          python python/tutorials/01-vector-add.py
      - name: Run gluon tutorials
        working-directory: ${GITHUB_WORKSPACE}
        run: |
          python python/tutorials/gluon/01-intro.py
      - name: Run interpreter tests
        working-directory: ./triton
        if: false
        run: make test-interpret
      - name: Run regression tests
        working-directory: ./triton
        if: false
        run: |
          make test-regression
      - name: Run C++ unittests
        working-directory: ./triton
        run: make test-cpp
      - name: Inspect cache directories
        run: |
          mkdir -p ~/.triton
          du -h -d 1 ~/.triton

          mkdir -p ~/.ccache
          du -h -d 1 ~/.ccache
