name: Update Triton Pin
permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: '0 8 * * *'  # Every day at 08:00 UTC
  workflow_dispatch:     # Allow manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout NPU Plugin
        uses: actions/checkout@v4
      - name: Fetch Triton upstream Commit Hash
        shell: bash
        run: |
          TRITON_COMMIT_HASH="$(cat triton.txt)"
          echo "Found Triton commit hash: ${TRITON_COMMIT_HASH}"
          echo "triton_commit_hash=${TRITON_COMMIT_HASH}" >> ${GITHUB_ENV}
      - name: Checkout Triton upstream repo
        uses: actions/checkout@v4
        with:
          repository: triton-lang/triton
          path: triton
      - name: Get the latest Triton commit hash
        working-directory: ./triton
        run: |
          git fetch origin
          LATEST_COMMIT=$(git rev-parse HEAD)
          echo "Latest Triton commit hash: ${LATEST_COMMIT}"
          echo "${LATEST_COMMIT}" > ../triton.txt
      - name: Compare hashes
        id: compare
        run: |
          if [ -f triton.txt ]; then
            new_hash=$(cat triton.txt)
          else
            new_hash=""
          fi
          old_hash=${{ env.triton_commit_hash }}

          echo "New hash: $new_hash"
          echo "Old hash: $old_hash"
          echo "new_triton_commit_hash=$new_hash" >> ${GITHUB_ENV}
          if [ "$new_hash" != "$old_hash" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      - name: Create PR Body
        run: |
          echo "Update `triton.txt` with the latest commit hash from Triton." > pr-body.md
      - name: Update format files
        if: steps.compare.outputs.changed == 'true'
        run: |
          cp ./triton/.clang-format .clang-format 
          cp ./triton/.pre-commit-config.yaml .pre-commit-config.yaml 
          cp ./triton/pyproject.toml pyproject.toml
      - name: Create pull request
        if: steps.compare.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: |
            triton.txt
            .clang-format
            .pre-commit-config.yaml
            pyproject.toml
          commit-message: "Update Triton commit hash to `${{ env.new_triton_commit_hash }}`"
          title: "[${{ github.event.schedule && 'Scheduled' || 'Manual' }}] Update Triton Commit Hash to `${{ env.new_triton_commit_hash }}`"
          body-path: pr-body.md
          branch: "update-triton-hash-${{ github.run_id }}"
          base: main
          delete-branch: true
